In [1]:
print("Hello Worlds")

Hello Worlds


In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [10]:
# 2x + 3y = 7
# 4x + 7y = 9
import numpy as np
from numpy import linalg as LA
A = [
    [2,3],
    [4,7]
    ]
B= [7,9]

A_numpy= np.array(A)
B_numpy = np.array(B)

# X , Y  = B_numpy @  LA.inv(A_numpy)
X , Y  = np.matmul(B_numpy,LA.inv(A_numpy))
print(X)
print(Y)






6.5
-1.5


In [11]:
# vectors
# 3i + 4j
# 4i + 7j
import numpy as np
from numpy import linalg as la
A = [3,4]
B = [4,7]

A_vector = np.array(A)
B_vector = np.array(B)

dot_productAB= np.dot(A_vector,B_vector)

print(dot_productAB)

40


In [12]:
# vectors
# 3i + 4j
# 4i + 7j
import numpy as np
from numpy import linalg as la
A = [3,4]
B = [4,7]

A_vector = np.array(A)
B_vector = np.array(B)

cross_productAB= np.vdot(A_vector,B_vector)

print(dot_productAB)

40


In [13]:
# vectors
# 3i + 4j
# 4i + 7j
import numpy as np
from numpy import linalg as la
A = [3,4]
B = [4,7]

A_vector = np.array(A)
B_vector = np.array(B)

cross_productAB= np.vecdot(A_vector,B_vector)

print(dot_productAB)

40


In [24]:
# vectors
# 3i + 4j
# 4i + 7j
import numpy as np
from numpy import linalg as la
A = list(range(1,13))
B = list(range(20,32))

print(A)
print(B)
# A_vector = np.array(np.arange(12)).reshape(2,2,3)
# B_vector = np.array(np.arange(12)).reshape(2,2,3)


A_vector = np.array(A).reshape(2,2,3)
B_vector = np.array(B).reshape(2,2,3)
cross_productAB= la.cross(A_vector,B_vector)

print(cross_productAB)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
[[[-19  38 -19]
  [-19  38 -19]]

 [[-19  38 -19]
  [-19  38 -19]]]


In [29]:
import numpy as np
from numpy import linalg as la
A = list(range(1,10))
B = list(range(20,29))

# print(A)
# print(B)
# A_vector = np.array(np.arange(12)).reshape(2,2,3)
# B_vector = np.array(np.arange(12)).reshape(2,2,3)

A_vector = np.array(A).reshape(3,3)
B_vector = np.array(B).reshape(3,3)
egvl, Egv= la.eig(A_vector)

print(egvl)
print(Egv)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [30]:
import numpy as np
from numpy import linalg as la
A_vector = np.array([2,3,5])
A_norm =la.norm(A_vector)
print(A_norm)

6.164414002968976


In [34]:
Unit_Vector =[]
for i in A_vector :
    unit = i / A_norm
    Unit_Vector.append(unit)

print(Unit_Vector)
i,j,k= Unit_Vector
print(i)

[np.float64(0.3244428422615251), np.float64(0.48666426339228763), np.float64(0.8111071056538127)]
0.3244428422615251
